# coding: utf-8

# flake8: noqa

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AdminApi",
    "AnonymousApi",
    "ApiKeyApi",
    "DefaultApi",
    "DeviceAuthorizationApi",
    "EmailOtpApi",
    "GenericOauthApi",
    "JwtApi",
    "MagicLinkApi",
    "McpApi",
    "MultiSessionApi",
    "OidcApi",
    "OneTapApi",
    "OneTimeTokenApi",
    "OrganizationApi",
    "PasskeyApi",
    "PhoneNumberApi",
    "SiweApi",
    "SsoApi",
    "TwoFactorApi",
    "UsernameApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Account",
    "AccountInfoPost200Response",
    "AccountInfoPost200ResponseUser",
    "AccountInfoPostRequest",
    "AdminHasPermissionPost200Response",
    "AdminHasPermissionPostRequest",
    "ApiKeyCreatePost200Response",
    "ApiKeyCreatePostRequest",
    "ApiKeyDeletePost200Response",
    "ApiKeyDeletePostRequest",
    "ApiKeyGetGet200Response",
    "ApiKeyListGet200ResponseInner",
    "ApiKeyUpdatePostRequest",
    "Apikey",
    "BanUserRequest",
    "ChangeEmailPost200Response",
    "ChangeEmailPostRequest",
    "ChangePasswordPost200Response",
    "ChangePasswordPostRequest",
    "CreateUserRequest",
    "DeleteUserCallbackGet200Response",
    "DeleteUserPost200Response",
    "DeleteUserPostRequest",
    "DeviceApprovePostRequest",
    "DeviceCode",
    "DeviceCodePost200Response",
    "DeviceCodePost400Response",
    "DeviceCodePostRequest",
    "DeviceDenyPostRequest",
    "DeviceGet200Response",
    "DeviceTokenPost400Response",
    "DeviceTokenPostRequest",
    "EmailOtpCheckVerificationOtpPostRequest",
    "EmailOtpResetPasswordPostRequest",
    "EmailOtpSendVerificationOtpPostRequest",
    "EmailOtpVerifyEmailPost200Response",
    "EmailOtpVerifyEmailPostRequest",
    "ForgetPasswordEmailOtpPost200Response",
    "ForgetPasswordEmailOtpPostRequest",
    "ForgetPasswordPost200Response",
    "ForgetPasswordPostRequest",
    "GetSessionGet200Response",
    "Invitation",
    "IsUsernameAvailablePostRequest",
    "Jwks",
    "JwksGet200Response",
    "JwksGet200ResponseKeysInner",
    "LinkSocialPost200Response",
    "LinkSocialPostRequest",
    "LinkSocialPostRequestIdToken",
    "ListAccountsGet200ResponseInner",
    "ListUserSessions200Response",
    "ListUserSessionsRequest",
    "ListUsers200Response",
    "McpRegisterPost200Response",
    "McpRegisterPostRequest",
    "Member",
    "MultiSessionRevokePostRequest",
    "MultiSessionSetActivePost200Response",
    "MultiSessionSetActivePostRequest",
    "Oauth2CallbackProviderIdGet200Response",
    "Oauth2ClientIdGet200Response",
    "Oauth2ConsentPost200Response",
    "Oauth2ConsentPostRequest",
    "Oauth2LinkPost200Response",
    "Oauth2LinkPostRequest",
    "Oauth2RegisterPost200Response",
    "Oauth2RegisterPostRequest",
    "Oauth2UserinfoGet200Response",
    "OauthAccessToken",
    "OauthApplication",
    "OauthConsent",
    "OkGet200Response",
    "OneTapCallbackPostRequest",
    "OneTimeTokenVerifyPostRequest",
    "Organization",
    "OrganizationAcceptInvitationPost200Response",
    "OrganizationAcceptInvitationPostRequest",
    "OrganizationCancelInvitationPostRequest",
    "OrganizationCheckSlugPostRequest",
    "OrganizationCreatePostRequest",
    "OrganizationDeletePostRequest",
    "OrganizationGetActiveMemberGet200Response",
    "OrganizationGetInvitationGet200Response",
    "OrganizationInviteMemberPost200Response",
    "OrganizationInviteMemberPostRequest",
    "OrganizationLeavePostRequest",
    "OrganizationRejectInvitationPost200Response",
    "OrganizationRejectInvitationPostRequest",
    "OrganizationRemoveMemberPost200Response",
    "OrganizationRemoveMemberPostRequest",
    "OrganizationSetActivePostRequest",
    "OrganizationUpdateMemberRolePostRequest",
    "OrganizationUpdatePostRequest",
    "OrganizationUpdatePostRequestData",
    "Passkey",
    "PasskeyDeletePasskeyPost200Response",
    "PasskeyDeletePasskeyPostRequest",
    "PasskeyGenerateAuthenticateOptionsPost200Response",
    "PasskeyGenerateRegisterOptionsGet200Response",
    "PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection",
    "PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner",
    "PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner",
    "PasskeyGenerateRegisterOptionsGet200ResponseRp",
    "PasskeyGenerateRegisterOptionsGet200ResponseUser",
    "PasskeyUpdatePasskeyPost200Response",
    "PasskeyUpdatePasskeyPostRequest",
    "PasskeyVerifyAuthenticationPostRequest",
    "PasskeyVerifyRegistrationPostRequest",
    "PhoneNumberForgetPasswordPost200Response",
    "PhoneNumberForgetPasswordPostRequest",
    "PhoneNumberRequestPasswordResetPostRequest",
    "PhoneNumberResetPasswordPost200Response",
    "PhoneNumberResetPasswordPostRequest",
    "PhoneNumberSendOtpPostRequest",
    "PhoneNumberVerifyPost200Response",
    "PhoneNumberVerifyPost200ResponseUser",
    "PhoneNumberVerifyPostRequest",
    "RefreshTokenPost200Response",
    "RefreshTokenPostRequest",
    "ResetPasswordPost200Response",
    "ResetPasswordPostRequest",
    "ResetPasswordTokenGet200Response",
    "RevokeOtherSessionsPost200Response",
    "RevokeSessionPost200Response",
    "RevokeSessionPostRequest",
    "RevokeSessionsPost200Response",
    "RevokeUserSessionRequest",
    "SendVerificationEmailPost200Response",
    "SendVerificationEmailPost400Response",
    "SendVerificationEmailPostRequest",
    "Session",
    "SetRole200Response",
    "SetRoleRequest",
    "SetUserPasswordRequest",
    "SignInAnonymousPost200Response",
    "SignInEmailOtpPostRequest",
    "SignInEmailPost200Response",
    "SignInEmailPost200ResponseUser",
    "SignInEmailPostRequest",
    "SignInMagicLinkPostRequest",
    "SignInOauth2Post200Response",
    "SignInOauth2PostRequest",
    "SignInPhoneNumberPostRequest",
    "SignInSsoPost200Response",
    "SignInSsoPostRequest",
    "SignInUsernamePost200Response",
    "SignInUsernamePostRequest",
    "SignOutPost200Response",
    "SignUpEmailPost200Response",
    "SignUpEmailPost200ResponseUser",
    "SignUpEmailPostRequest",
    "SiweNoncePostRequest",
    "SiweVerifyPostRequest",
    "SocialSignIn200Response",
    "SocialSignIn400Response",
    "SocialSignIn403Response",
    "SocialSignInRequest",
    "SocialSignInRequestIdToken",
    "SsoProvider",
    "SsoRegisterPost200Response",
    "SsoRegisterPost200ResponseOidcConfig",
    "SsoRegisterPost200ResponseOidcConfigMapping",
    "SsoRegisterPostRequest",
    "SsoRegisterPostRequestMapping",
    "SsoRegisterPostRequestOidcConfig",
    "SsoRegisterPostRequestSamlConfig",
    "SsoRegisterPostRequestSamlConfigIdpMetadata",
    "SsoRegisterPostRequestSamlConfigSpMetadata",
    "SsoSaml2CallbackProviderIdPostRequest",
    "TwoFactor",
    "TwoFactorEnablePost200Response",
    "TwoFactorEnablePostRequest",
    "TwoFactorGenerateBackupCodesPost200Response",
    "TwoFactorGenerateBackupCodesPostRequest",
    "TwoFactorGetTotpUriPost200Response",
    "TwoFactorGetTotpUriPostRequest",
    "TwoFactorVerifyBackupCodePost200Response",
    "TwoFactorVerifyBackupCodePost200ResponseSession",
    "TwoFactorVerifyBackupCodePost200ResponseUser",
    "TwoFactorVerifyBackupCodePostRequest",
    "TwoFactorVerifyOtpPost200Response",
    "TwoFactorVerifyOtpPost200ResponseUser",
    "TwoFactorVerifyOtpPostRequest",
    "TwoFactorVerifyTotpPostRequest",
    "UnlinkAccountPostRequest",
    "UpdateUserPost200Response",
    "UpdateUserPostRequest",
    "UpdateUserRequest",
    "User",
    "Verification",
    "VerifyEmailGet200Response",
    "VerifyEmailGet200ResponseUser",
    "WalletAddress",
]

# import apis into sdk package
from better_auth.api.admin_api import AdminApi as AdminApi
from better_auth.api.anonymous_api import AnonymousApi as AnonymousApi
from better_auth.api.api_key_api import ApiKeyApi as ApiKeyApi
from better_auth.api.default_api import DefaultApi as DefaultApi
from better_auth.api.device_authorization_api import DeviceAuthorizationApi as DeviceAuthorizationApi
from better_auth.api.email_otp_api import EmailOtpApi as EmailOtpApi
from better_auth.api.generic_oauth_api import GenericOauthApi as GenericOauthApi
from better_auth.api.jwt_api import JwtApi as JwtApi
from better_auth.api.magic_link_api import MagicLinkApi as MagicLinkApi
from better_auth.api.mcp_api import McpApi as McpApi
from better_auth.api.multi_session_api import MultiSessionApi as MultiSessionApi
from better_auth.api.oidc_api import OidcApi as OidcApi
from better_auth.api.one_tap_api import OneTapApi as OneTapApi
from better_auth.api.one_time_token_api import OneTimeTokenApi as OneTimeTokenApi
from better_auth.api.organization_api import OrganizationApi as OrganizationApi
from better_auth.api.passkey_api import PasskeyApi as PasskeyApi
from better_auth.api.phone_number_api import PhoneNumberApi as PhoneNumberApi
from better_auth.api.siwe_api import SiweApi as SiweApi
from better_auth.api.sso_api import SsoApi as SsoApi
from better_auth.api.two_factor_api import TwoFactorApi as TwoFactorApi
from better_auth.api.username_api import UsernameApi as UsernameApi

# import ApiClient
from better_auth.api_response import ApiResponse as ApiResponse
from better_auth.api_client import ApiClient as ApiClient
from better_auth.configuration import Configuration as Configuration
from better_auth.exceptions import OpenApiException as OpenApiException
from better_auth.exceptions import ApiTypeError as ApiTypeError
from better_auth.exceptions import ApiValueError as ApiValueError
from better_auth.exceptions import ApiKeyError as ApiKeyError
from better_auth.exceptions import ApiAttributeError as ApiAttributeError
from better_auth.exceptions import ApiException as ApiException

# import models into sdk package
from better_auth.models.account import Account as Account
from better_auth.models.account_info_post200_response import AccountInfoPost200Response as AccountInfoPost200Response
from better_auth.models.account_info_post200_response_user import AccountInfoPost200ResponseUser as AccountInfoPost200ResponseUser
from better_auth.models.account_info_post_request import AccountInfoPostRequest as AccountInfoPostRequest
from better_auth.models.admin_has_permission_post200_response import AdminHasPermissionPost200Response as AdminHasPermissionPost200Response
from better_auth.models.admin_has_permission_post_request import AdminHasPermissionPostRequest as AdminHasPermissionPostRequest
from better_auth.models.api_key_create_post200_response import ApiKeyCreatePost200Response as ApiKeyCreatePost200Response
from better_auth.models.api_key_create_post_request import ApiKeyCreatePostRequest as ApiKeyCreatePostRequest
from better_auth.models.api_key_delete_post200_response import ApiKeyDeletePost200Response as ApiKeyDeletePost200Response
from better_auth.models.api_key_delete_post_request import ApiKeyDeletePostRequest as ApiKeyDeletePostRequest
from better_auth.models.api_key_get_get200_response import ApiKeyGetGet200Response as ApiKeyGetGet200Response
from better_auth.models.api_key_list_get200_response_inner import ApiKeyListGet200ResponseInner as ApiKeyListGet200ResponseInner
from better_auth.models.api_key_update_post_request import ApiKeyUpdatePostRequest as ApiKeyUpdatePostRequest
from better_auth.models.apikey import Apikey as Apikey
from better_auth.models.ban_user_request import BanUserRequest as BanUserRequest
from better_auth.models.change_email_post200_response import ChangeEmailPost200Response as ChangeEmailPost200Response
from better_auth.models.change_email_post_request import ChangeEmailPostRequest as ChangeEmailPostRequest
from better_auth.models.change_password_post200_response import ChangePasswordPost200Response as ChangePasswordPost200Response
from better_auth.models.change_password_post_request import ChangePasswordPostRequest as ChangePasswordPostRequest
from better_auth.models.create_user_request import CreateUserRequest as CreateUserRequest
from better_auth.models.delete_user_callback_get200_response import DeleteUserCallbackGet200Response as DeleteUserCallbackGet200Response
from better_auth.models.delete_user_post200_response import DeleteUserPost200Response as DeleteUserPost200Response
from better_auth.models.delete_user_post_request import DeleteUserPostRequest as DeleteUserPostRequest
from better_auth.models.device_approve_post_request import DeviceApprovePostRequest as DeviceApprovePostRequest
from better_auth.models.device_code import DeviceCode as DeviceCode
from better_auth.models.device_code_post200_response import DeviceCodePost200Response as DeviceCodePost200Response
from better_auth.models.device_code_post400_response import DeviceCodePost400Response as DeviceCodePost400Response
from better_auth.models.device_code_post_request import DeviceCodePostRequest as DeviceCodePostRequest
from better_auth.models.device_deny_post_request import DeviceDenyPostRequest as DeviceDenyPostRequest
from better_auth.models.device_get200_response import DeviceGet200Response as DeviceGet200Response
from better_auth.models.device_token_post400_response import DeviceTokenPost400Response as DeviceTokenPost400Response
from better_auth.models.device_token_post_request import DeviceTokenPostRequest as DeviceTokenPostRequest
from better_auth.models.email_otp_check_verification_otp_post_request import EmailOtpCheckVerificationOtpPostRequest as EmailOtpCheckVerificationOtpPostRequest
from better_auth.models.email_otp_reset_password_post_request import EmailOtpResetPasswordPostRequest as EmailOtpResetPasswordPostRequest
from better_auth.models.email_otp_send_verification_otp_post_request import EmailOtpSendVerificationOtpPostRequest as EmailOtpSendVerificationOtpPostRequest
from better_auth.models.email_otp_verify_email_post200_response import EmailOtpVerifyEmailPost200Response as EmailOtpVerifyEmailPost200Response
from better_auth.models.email_otp_verify_email_post_request import EmailOtpVerifyEmailPostRequest as EmailOtpVerifyEmailPostRequest
from better_auth.models.forget_password_email_otp_post200_response import ForgetPasswordEmailOtpPost200Response as ForgetPasswordEmailOtpPost200Response
from better_auth.models.forget_password_email_otp_post_request import ForgetPasswordEmailOtpPostRequest as ForgetPasswordEmailOtpPostRequest
from better_auth.models.forget_password_post200_response import ForgetPasswordPost200Response as ForgetPasswordPost200Response
from better_auth.models.forget_password_post_request import ForgetPasswordPostRequest as ForgetPasswordPostRequest
from better_auth.models.get_session_get200_response import GetSessionGet200Response as GetSessionGet200Response
from better_auth.models.invitation import Invitation as Invitation
from better_auth.models.is_username_available_post_request import IsUsernameAvailablePostRequest as IsUsernameAvailablePostRequest
from better_auth.models.jwks import Jwks as Jwks
from better_auth.models.jwks_get200_response import JwksGet200Response as JwksGet200Response
from better_auth.models.jwks_get200_response_keys_inner import JwksGet200ResponseKeysInner as JwksGet200ResponseKeysInner
from better_auth.models.link_social_post200_response import LinkSocialPost200Response as LinkSocialPost200Response
from better_auth.models.link_social_post_request import LinkSocialPostRequest as LinkSocialPostRequest
from better_auth.models.link_social_post_request_id_token import LinkSocialPostRequestIdToken as LinkSocialPostRequestIdToken
from better_auth.models.list_accounts_get200_response_inner import ListAccountsGet200ResponseInner as ListAccountsGet200ResponseInner
from better_auth.models.list_user_sessions200_response import ListUserSessions200Response as ListUserSessions200Response
from better_auth.models.list_user_sessions_request import ListUserSessionsRequest as ListUserSessionsRequest
from better_auth.models.list_users200_response import ListUsers200Response as ListUsers200Response
from better_auth.models.mcp_register_post200_response import McpRegisterPost200Response as McpRegisterPost200Response
from better_auth.models.mcp_register_post_request import McpRegisterPostRequest as McpRegisterPostRequest
from better_auth.models.member import Member as Member
from better_auth.models.multi_session_revoke_post_request import MultiSessionRevokePostRequest as MultiSessionRevokePostRequest
from better_auth.models.multi_session_set_active_post200_response import MultiSessionSetActivePost200Response as MultiSessionSetActivePost200Response
from better_auth.models.multi_session_set_active_post_request import MultiSessionSetActivePostRequest as MultiSessionSetActivePostRequest
from better_auth.models.oauth2_callback_provider_id_get200_response import Oauth2CallbackProviderIdGet200Response as Oauth2CallbackProviderIdGet200Response
from better_auth.models.oauth2_client_id_get200_response import Oauth2ClientIdGet200Response as Oauth2ClientIdGet200Response
from better_auth.models.oauth2_consent_post200_response import Oauth2ConsentPost200Response as Oauth2ConsentPost200Response
from better_auth.models.oauth2_consent_post_request import Oauth2ConsentPostRequest as Oauth2ConsentPostRequest
from better_auth.models.oauth2_link_post200_response import Oauth2LinkPost200Response as Oauth2LinkPost200Response
from better_auth.models.oauth2_link_post_request import Oauth2LinkPostRequest as Oauth2LinkPostRequest
from better_auth.models.oauth2_register_post200_response import Oauth2RegisterPost200Response as Oauth2RegisterPost200Response
from better_auth.models.oauth2_register_post_request import Oauth2RegisterPostRequest as Oauth2RegisterPostRequest
from better_auth.models.oauth2_userinfo_get200_response import Oauth2UserinfoGet200Response as Oauth2UserinfoGet200Response
from better_auth.models.oauth_access_token import OauthAccessToken as OauthAccessToken
from better_auth.models.oauth_application import OauthApplication as OauthApplication
from better_auth.models.oauth_consent import OauthConsent as OauthConsent
from better_auth.models.ok_get200_response import OkGet200Response as OkGet200Response
from better_auth.models.one_tap_callback_post_request import OneTapCallbackPostRequest as OneTapCallbackPostRequest
from better_auth.models.one_time_token_verify_post_request import OneTimeTokenVerifyPostRequest as OneTimeTokenVerifyPostRequest
from better_auth.models.organization import Organization as Organization
from better_auth.models.organization_accept_invitation_post200_response import OrganizationAcceptInvitationPost200Response as OrganizationAcceptInvitationPost200Response
from better_auth.models.organization_accept_invitation_post_request import OrganizationAcceptInvitationPostRequest as OrganizationAcceptInvitationPostRequest
from better_auth.models.organization_cancel_invitation_post_request import OrganizationCancelInvitationPostRequest as OrganizationCancelInvitationPostRequest
from better_auth.models.organization_check_slug_post_request import OrganizationCheckSlugPostRequest as OrganizationCheckSlugPostRequest
from better_auth.models.organization_create_post_request import OrganizationCreatePostRequest as OrganizationCreatePostRequest
from better_auth.models.organization_delete_post_request import OrganizationDeletePostRequest as OrganizationDeletePostRequest
from better_auth.models.organization_get_active_member_get200_response import OrganizationGetActiveMemberGet200Response as OrganizationGetActiveMemberGet200Response
from better_auth.models.organization_get_invitation_get200_response import OrganizationGetInvitationGet200Response as OrganizationGetInvitationGet200Response
from better_auth.models.organization_invite_member_post200_response import OrganizationInviteMemberPost200Response as OrganizationInviteMemberPost200Response
from better_auth.models.organization_invite_member_post_request import OrganizationInviteMemberPostRequest as OrganizationInviteMemberPostRequest
from better_auth.models.organization_leave_post_request import OrganizationLeavePostRequest as OrganizationLeavePostRequest
from better_auth.models.organization_reject_invitation_post200_response import OrganizationRejectInvitationPost200Response as OrganizationRejectInvitationPost200Response
from better_auth.models.organization_reject_invitation_post_request import OrganizationRejectInvitationPostRequest as OrganizationRejectInvitationPostRequest
from better_auth.models.organization_remove_member_post200_response import OrganizationRemoveMemberPost200Response as OrganizationRemoveMemberPost200Response
from better_auth.models.organization_remove_member_post_request import OrganizationRemoveMemberPostRequest as OrganizationRemoveMemberPostRequest
from better_auth.models.organization_set_active_post_request import OrganizationSetActivePostRequest as OrganizationSetActivePostRequest
from better_auth.models.organization_update_member_role_post_request import OrganizationUpdateMemberRolePostRequest as OrganizationUpdateMemberRolePostRequest
from better_auth.models.organization_update_post_request import OrganizationUpdatePostRequest as OrganizationUpdatePostRequest
from better_auth.models.organization_update_post_request_data import OrganizationUpdatePostRequestData as OrganizationUpdatePostRequestData
from better_auth.models.passkey import Passkey as Passkey
from better_auth.models.passkey_delete_passkey_post200_response import PasskeyDeletePasskeyPost200Response as PasskeyDeletePasskeyPost200Response
from better_auth.models.passkey_delete_passkey_post_request import PasskeyDeletePasskeyPostRequest as PasskeyDeletePasskeyPostRequest
from better_auth.models.passkey_generate_authenticate_options_post200_response import PasskeyGenerateAuthenticateOptionsPost200Response as PasskeyGenerateAuthenticateOptionsPost200Response
from better_auth.models.passkey_generate_register_options_get200_response import PasskeyGenerateRegisterOptionsGet200Response as PasskeyGenerateRegisterOptionsGet200Response
from better_auth.models.passkey_generate_register_options_get200_response_authenticator_selection import PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection as PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection
from better_auth.models.passkey_generate_register_options_get200_response_exclude_credentials_inner import PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner as PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner
from better_auth.models.passkey_generate_register_options_get200_response_pub_key_cred_params_inner import PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner as PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner
from better_auth.models.passkey_generate_register_options_get200_response_rp import PasskeyGenerateRegisterOptionsGet200ResponseRp as PasskeyGenerateRegisterOptionsGet200ResponseRp
from better_auth.models.passkey_generate_register_options_get200_response_user import PasskeyGenerateRegisterOptionsGet200ResponseUser as PasskeyGenerateRegisterOptionsGet200ResponseUser
from better_auth.models.passkey_update_passkey_post200_response import PasskeyUpdatePasskeyPost200Response as PasskeyUpdatePasskeyPost200Response
from better_auth.models.passkey_update_passkey_post_request import PasskeyUpdatePasskeyPostRequest as PasskeyUpdatePasskeyPostRequest
from better_auth.models.passkey_verify_authentication_post_request import PasskeyVerifyAuthenticationPostRequest as PasskeyVerifyAuthenticationPostRequest
from better_auth.models.passkey_verify_registration_post_request import PasskeyVerifyRegistrationPostRequest as PasskeyVerifyRegistrationPostRequest
from better_auth.models.phone_number_forget_password_post200_response import PhoneNumberForgetPasswordPost200Response as PhoneNumberForgetPasswordPost200Response
from better_auth.models.phone_number_forget_password_post_request import PhoneNumberForgetPasswordPostRequest as PhoneNumberForgetPasswordPostRequest
from better_auth.models.phone_number_request_password_reset_post_request import PhoneNumberRequestPasswordResetPostRequest as PhoneNumberRequestPasswordResetPostRequest
from better_auth.models.phone_number_reset_password_post200_response import PhoneNumberResetPasswordPost200Response as PhoneNumberResetPasswordPost200Response
from better_auth.models.phone_number_reset_password_post_request import PhoneNumberResetPasswordPostRequest as PhoneNumberResetPasswordPostRequest
from better_auth.models.phone_number_send_otp_post_request import PhoneNumberSendOtpPostRequest as PhoneNumberSendOtpPostRequest
from better_auth.models.phone_number_verify_post200_response import PhoneNumberVerifyPost200Response as PhoneNumberVerifyPost200Response
from better_auth.models.phone_number_verify_post200_response_user import PhoneNumberVerifyPost200ResponseUser as PhoneNumberVerifyPost200ResponseUser
from better_auth.models.phone_number_verify_post_request import PhoneNumberVerifyPostRequest as PhoneNumberVerifyPostRequest
from better_auth.models.refresh_token_post200_response import RefreshTokenPost200Response as RefreshTokenPost200Response
from better_auth.models.refresh_token_post_request import RefreshTokenPostRequest as RefreshTokenPostRequest
from better_auth.models.reset_password_post200_response import ResetPasswordPost200Response as ResetPasswordPost200Response
from better_auth.models.reset_password_post_request import ResetPasswordPostRequest as ResetPasswordPostRequest
from better_auth.models.reset_password_token_get200_response import ResetPasswordTokenGet200Response as ResetPasswordTokenGet200Response
from better_auth.models.revoke_other_sessions_post200_response import RevokeOtherSessionsPost200Response as RevokeOtherSessionsPost200Response
from better_auth.models.revoke_session_post200_response import RevokeSessionPost200Response as RevokeSessionPost200Response
from better_auth.models.revoke_session_post_request import RevokeSessionPostRequest as RevokeSessionPostRequest
from better_auth.models.revoke_sessions_post200_response import RevokeSessionsPost200Response as RevokeSessionsPost200Response
from better_auth.models.revoke_user_session_request import RevokeUserSessionRequest as RevokeUserSessionRequest
from better_auth.models.send_verification_email_post200_response import SendVerificationEmailPost200Response as SendVerificationEmailPost200Response
from better_auth.models.send_verification_email_post400_response import SendVerificationEmailPost400Response as SendVerificationEmailPost400Response
from better_auth.models.send_verification_email_post_request import SendVerificationEmailPostRequest as SendVerificationEmailPostRequest
from better_auth.models.session import Session as Session
from better_auth.models.set_role200_response import SetRole200Response as SetRole200Response
from better_auth.models.set_role_request import SetRoleRequest as SetRoleRequest
from better_auth.models.set_user_password_request import SetUserPasswordRequest as SetUserPasswordRequest
from better_auth.models.sign_in_anonymous_post200_response import SignInAnonymousPost200Response as SignInAnonymousPost200Response
from better_auth.models.sign_in_email_otp_post_request import SignInEmailOtpPostRequest as SignInEmailOtpPostRequest
from better_auth.models.sign_in_email_post200_response import SignInEmailPost200Response as SignInEmailPost200Response
from better_auth.models.sign_in_email_post200_response_user import SignInEmailPost200ResponseUser as SignInEmailPost200ResponseUser
from better_auth.models.sign_in_email_post_request import SignInEmailPostRequest as SignInEmailPostRequest
from better_auth.models.sign_in_magic_link_post_request import SignInMagicLinkPostRequest as SignInMagicLinkPostRequest
from better_auth.models.sign_in_oauth2_post200_response import SignInOauth2Post200Response as SignInOauth2Post200Response
from better_auth.models.sign_in_oauth2_post_request import SignInOauth2PostRequest as SignInOauth2PostRequest
from better_auth.models.sign_in_phone_number_post_request import SignInPhoneNumberPostRequest as SignInPhoneNumberPostRequest
from better_auth.models.sign_in_sso_post200_response import SignInSsoPost200Response as SignInSsoPost200Response
from better_auth.models.sign_in_sso_post_request import SignInSsoPostRequest as SignInSsoPostRequest
from better_auth.models.sign_in_username_post200_response import SignInUsernamePost200Response as SignInUsernamePost200Response
from better_auth.models.sign_in_username_post_request import SignInUsernamePostRequest as SignInUsernamePostRequest
from better_auth.models.sign_out_post200_response import SignOutPost200Response as SignOutPost200Response
from better_auth.models.sign_up_email_post200_response import SignUpEmailPost200Response as SignUpEmailPost200Response
from better_auth.models.sign_up_email_post200_response_user import SignUpEmailPost200ResponseUser as SignUpEmailPost200ResponseUser
from better_auth.models.sign_up_email_post_request import SignUpEmailPostRequest as SignUpEmailPostRequest
from better_auth.models.siwe_nonce_post_request import SiweNoncePostRequest as SiweNoncePostRequest
from better_auth.models.siwe_verify_post_request import SiweVerifyPostRequest as SiweVerifyPostRequest
from better_auth.models.social_sign_in200_response import SocialSignIn200Response as SocialSignIn200Response
from better_auth.models.social_sign_in400_response import SocialSignIn400Response as SocialSignIn400Response
from better_auth.models.social_sign_in403_response import SocialSignIn403Response as SocialSignIn403Response
from better_auth.models.social_sign_in_request import SocialSignInRequest as SocialSignInRequest
from better_auth.models.social_sign_in_request_id_token import SocialSignInRequestIdToken as SocialSignInRequestIdToken
from better_auth.models.sso_provider import SsoProvider as SsoProvider
from better_auth.models.sso_register_post200_response import SsoRegisterPost200Response as SsoRegisterPost200Response
from better_auth.models.sso_register_post200_response_oidc_config import SsoRegisterPost200ResponseOidcConfig as SsoRegisterPost200ResponseOidcConfig
from better_auth.models.sso_register_post200_response_oidc_config_mapping import SsoRegisterPost200ResponseOidcConfigMapping as SsoRegisterPost200ResponseOidcConfigMapping
from better_auth.models.sso_register_post_request import SsoRegisterPostRequest as SsoRegisterPostRequest
from better_auth.models.sso_register_post_request_mapping import SsoRegisterPostRequestMapping as SsoRegisterPostRequestMapping
from better_auth.models.sso_register_post_request_oidc_config import SsoRegisterPostRequestOidcConfig as SsoRegisterPostRequestOidcConfig
from better_auth.models.sso_register_post_request_saml_config import SsoRegisterPostRequestSamlConfig as SsoRegisterPostRequestSamlConfig
from better_auth.models.sso_register_post_request_saml_config_idp_metadata import SsoRegisterPostRequestSamlConfigIdpMetadata as SsoRegisterPostRequestSamlConfigIdpMetadata
from better_auth.models.sso_register_post_request_saml_config_sp_metadata import SsoRegisterPostRequestSamlConfigSpMetadata as SsoRegisterPostRequestSamlConfigSpMetadata
from better_auth.models.sso_saml2_callback_provider_id_post_request import SsoSaml2CallbackProviderIdPostRequest as SsoSaml2CallbackProviderIdPostRequest
from better_auth.models.two_factor import TwoFactor as TwoFactor
from better_auth.models.two_factor_enable_post200_response import TwoFactorEnablePost200Response as TwoFactorEnablePost200Response
from better_auth.models.two_factor_enable_post_request import TwoFactorEnablePostRequest as TwoFactorEnablePostRequest
from better_auth.models.two_factor_generate_backup_codes_post200_response import TwoFactorGenerateBackupCodesPost200Response as TwoFactorGenerateBackupCodesPost200Response
from better_auth.models.two_factor_generate_backup_codes_post_request import TwoFactorGenerateBackupCodesPostRequest as TwoFactorGenerateBackupCodesPostRequest
from better_auth.models.two_factor_get_totp_uri_post200_response import TwoFactorGetTotpUriPost200Response as TwoFactorGetTotpUriPost200Response
from better_auth.models.two_factor_get_totp_uri_post_request import TwoFactorGetTotpUriPostRequest as TwoFactorGetTotpUriPostRequest
from better_auth.models.two_factor_verify_backup_code_post200_response import TwoFactorVerifyBackupCodePost200Response as TwoFactorVerifyBackupCodePost200Response
from better_auth.models.two_factor_verify_backup_code_post200_response_session import TwoFactorVerifyBackupCodePost200ResponseSession as TwoFactorVerifyBackupCodePost200ResponseSession
from better_auth.models.two_factor_verify_backup_code_post200_response_user import TwoFactorVerifyBackupCodePost200ResponseUser as TwoFactorVerifyBackupCodePost200ResponseUser
from better_auth.models.two_factor_verify_backup_code_post_request import TwoFactorVerifyBackupCodePostRequest as TwoFactorVerifyBackupCodePostRequest
from better_auth.models.two_factor_verify_otp_post200_response import TwoFactorVerifyOtpPost200Response as TwoFactorVerifyOtpPost200Response
from better_auth.models.two_factor_verify_otp_post200_response_user import TwoFactorVerifyOtpPost200ResponseUser as TwoFactorVerifyOtpPost200ResponseUser
from better_auth.models.two_factor_verify_otp_post_request import TwoFactorVerifyOtpPostRequest as TwoFactorVerifyOtpPostRequest
from better_auth.models.two_factor_verify_totp_post_request import TwoFactorVerifyTotpPostRequest as TwoFactorVerifyTotpPostRequest
from better_auth.models.unlink_account_post_request import UnlinkAccountPostRequest as UnlinkAccountPostRequest
from better_auth.models.update_user_post200_response import UpdateUserPost200Response as UpdateUserPost200Response
from better_auth.models.update_user_post_request import UpdateUserPostRequest as UpdateUserPostRequest
from better_auth.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from better_auth.models.user import User as User
from better_auth.models.verification import Verification as Verification
from better_auth.models.verify_email_get200_response import VerifyEmailGet200Response as VerifyEmailGet200Response
from better_auth.models.verify_email_get200_response_user import VerifyEmailGet200ResponseUser as VerifyEmailGet200ResponseUser
from better_auth.models.wallet_address import WalletAddress as WalletAddress
