# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.phone_number_reset_password_post200_response import PhoneNumberResetPasswordPost200Response

class TestPhoneNumberResetPasswordPost200Response(unittest.TestCase):
    """PhoneNumberResetPasswordPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumberResetPasswordPost200Response:
        """Test PhoneNumberResetPasswordPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumberResetPasswordPost200Response`
        """
        model = PhoneNumberResetPasswordPost200Response()
        if include_optional:
            return PhoneNumberResetPasswordPost200Response(
                status = true
            )
        else:
            return PhoneNumberResetPasswordPost200Response(
                status = true,
        )
        """

    def testPhoneNumberResetPasswordPost200Response(self):
        """Test PhoneNumberResetPasswordPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
