# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.oauth2_callback_provider_id_get200_response import Oauth2CallbackProviderIdGet200Response

class TestOauth2CallbackProviderIdGet200Response(unittest.TestCase):
    """Oauth2CallbackProviderIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2CallbackProviderIdGet200Response:
        """Test Oauth2CallbackProviderIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2CallbackProviderIdGet200Response`
        """
        model = Oauth2CallbackProviderIdGet200Response()
        if include_optional:
            return Oauth2CallbackProviderIdGet200Response(
                url = ''
            )
        else:
            return Oauth2CallbackProviderIdGet200Response(
        )
        """

    def testOauth2CallbackProviderIdGet200Response(self):
        """Test Oauth2CallbackProviderIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
