# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_generate_register_options_get200_response_user import PasskeyGenerateRegisterOptionsGet200ResponseUser

class TestPasskeyGenerateRegisterOptionsGet200ResponseUser(unittest.TestCase):
    """PasskeyGenerateRegisterOptionsGet200ResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyGenerateRegisterOptionsGet200ResponseUser:
        """Test PasskeyGenerateRegisterOptionsGet200ResponseUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyGenerateRegisterOptionsGet200ResponseUser`
        """
        model = PasskeyGenerateRegisterOptionsGet200ResponseUser()
        if include_optional:
            return PasskeyGenerateRegisterOptionsGet200ResponseUser(
                id = '',
                name = '',
                display_name = ''
            )
        else:
            return PasskeyGenerateRegisterOptionsGet200ResponseUser(
        )
        """

    def testPasskeyGenerateRegisterOptionsGet200ResponseUser(self):
        """Test PasskeyGenerateRegisterOptionsGet200ResponseUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
