# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.list_user_sessions200_response import ListUserSessions200Response

class TestListUserSessions200Response(unittest.TestCase):
    """ListUserSessions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUserSessions200Response:
        """Test ListUserSessions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUserSessions200Response`
        """
        model = ListUserSessions200Response()
        if include_optional:
            return ListUserSessions200Response(
                sessions = [
                    better_auth.models.session.Session(
                        id = '', 
                        expires_at = '', 
                        token = '', 
                        created_at = 'Generated at runtime', 
                        updated_at = '', 
                        ip_address = '', 
                        user_agent = '', 
                        user_id = '', 
                        impersonated_by = '', 
                        active_organization_id = '', )
                    ]
            )
        else:
            return ListUserSessions200Response(
        )
        """

    def testListUserSessions200Response(self):
        """Test ListUserSessions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
