# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sso_register_post_request_oidc_config import SsoRegisterPostRequestOidcConfig

class TestSsoRegisterPostRequestOidcConfig(unittest.TestCase):
    """SsoRegisterPostRequestOidcConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SsoRegisterPostRequestOidcConfig:
        """Test SsoRegisterPostRequestOidcConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SsoRegisterPostRequestOidcConfig`
        """
        model = SsoRegisterPostRequestOidcConfig()
        if include_optional:
            return SsoRegisterPostRequestOidcConfig(
                client_id = '',
                client_secret = '',
                authorization_endpoint = '',
                token_endpoint = '',
                user_info_endpoint = '',
                token_endpoint_authentication = '',
                jwks_endpoint = '',
                discovery_endpoint = '',
                scopes = [
                    null
                    ],
                pkce = ''
            )
        else:
            return SsoRegisterPostRequestOidcConfig(
                client_id = '',
                client_secret = '',
        )
        """

    def testSsoRegisterPostRequestOidcConfig(self):
        """Test SsoRegisterPostRequestOidcConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
