# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.verify_email_get200_response import VerifyEmailGet200Response

class TestVerifyEmailGet200Response(unittest.TestCase):
    """VerifyEmailGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyEmailGet200Response:
        """Test VerifyEmailGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyEmailGet200Response`
        """
        model = VerifyEmailGet200Response()
        if include_optional:
            return VerifyEmailGet200Response(
                user = better_auth.models._verify_email_get_200_response_user._verify_email_get_200_response_user(
                    id = '', 
                    email = '', 
                    name = '', 
                    image = '', 
                    email_verified = True, 
                    created_at = '', 
                    updated_at = '', ),
                status = True
            )
        else:
            return VerifyEmailGet200Response(
                user = better_auth.models._verify_email_get_200_response_user._verify_email_get_200_response_user(
                    id = '', 
                    email = '', 
                    name = '', 
                    image = '', 
                    email_verified = True, 
                    created_at = '', 
                    updated_at = '', ),
                status = True,
        )
        """

    def testVerifyEmailGet200Response(self):
        """Test VerifyEmailGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
