# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.oauth2_userinfo_get200_response import Oauth2UserinfoGet200Response

class TestOauth2UserinfoGet200Response(unittest.TestCase):
    """Oauth2UserinfoGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2UserinfoGet200Response:
        """Test Oauth2UserinfoGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2UserinfoGet200Response`
        """
        model = Oauth2UserinfoGet200Response()
        if include_optional:
            return Oauth2UserinfoGet200Response(
                sub = '',
                email = '',
                name = '',
                picture = '',
                given_name = '',
                family_name = '',
                email_verified = True
            )
        else:
            return Oauth2UserinfoGet200Response(
                sub = '',
        )
        """

    def testOauth2UserinfoGet200Response(self):
        """Test Oauth2UserinfoGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
