# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.social_sign_in200_response import SocialSignIn200Response

class TestSocialSignIn200Response(unittest.TestCase):
    """SocialSignIn200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SocialSignIn200Response:
        """Test SocialSignIn200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SocialSignIn200Response`
        """
        model = SocialSignIn200Response()
        if include_optional:
            return SocialSignIn200Response(
                redirect = false,
                token = ''
            )
        else:
            return SocialSignIn200Response(
                redirect = false,
                token = '',
        )
        """

    def testSocialSignIn200Response(self):
        """Test SocialSignIn200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
