# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.organization_delete_post_request import OrganizationDeletePostRequest

class TestOrganizationDeletePostRequest(unittest.TestCase):
    """OrganizationDeletePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationDeletePostRequest:
        """Test OrganizationDeletePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationDeletePostRequest`
        """
        model = OrganizationDeletePostRequest()
        if include_optional:
            return OrganizationDeletePostRequest(
                organization_id = ''
            )
        else:
            return OrganizationDeletePostRequest(
                organization_id = '',
        )
        """

    def testOrganizationDeletePostRequest(self):
        """Test OrganizationDeletePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
