# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.account_info_post200_response_user import AccountInfoPost200ResponseUser

class TestAccountInfoPost200ResponseUser(unittest.TestCase):
    """AccountInfoPost200ResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountInfoPost200ResponseUser:
        """Test AccountInfoPost200ResponseUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountInfoPost200ResponseUser`
        """
        model = AccountInfoPost200ResponseUser()
        if include_optional:
            return AccountInfoPost200ResponseUser(
                id = '',
                name = '',
                email = '',
                image = '',
                email_verified = True
            )
        else:
            return AccountInfoPost200ResponseUser(
                id = '',
                email_verified = True,
        )
        """

    def testAccountInfoPost200ResponseUser(self):
        """Test AccountInfoPost200ResponseUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
