# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.update_user_post200_response import UpdateUserPost200Response

class TestUpdateUserPost200Response(unittest.TestCase):
    """UpdateUserPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserPost200Response:
        """Test UpdateUserPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserPost200Response`
        """
        model = UpdateUserPost200Response()
        if include_optional:
            return UpdateUserPost200Response(
                status = True
            )
        else:
            return UpdateUserPost200Response(
        )
        """

    def testUpdateUserPost200Response(self):
        """Test UpdateUserPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
