# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sso_register_post_request_saml_config_sp_metadata import SsoRegisterPostRequestSamlConfigSpMetadata

class TestSsoRegisterPostRequestSamlConfigSpMetadata(unittest.TestCase):
    """SsoRegisterPostRequestSamlConfigSpMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SsoRegisterPostRequestSamlConfigSpMetadata:
        """Test SsoRegisterPostRequestSamlConfigSpMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SsoRegisterPostRequestSamlConfigSpMetadata`
        """
        model = SsoRegisterPostRequestSamlConfigSpMetadata()
        if include_optional:
            return SsoRegisterPostRequestSamlConfigSpMetadata(
                metadata = '',
                binding = '',
                private_key = '',
                private_key_pass = '',
                is_assertion_encrypted = True,
                enc_private_key = '',
                enc_private_key_pass = ''
            )
        else:
            return SsoRegisterPostRequestSamlConfigSpMetadata(
                metadata = '',
        )
        """

    def testSsoRegisterPostRequestSamlConfigSpMetadata(self):
        """Test SsoRegisterPostRequestSamlConfigSpMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
