# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.organization_accept_invitation_post200_response import OrganizationAcceptInvitationPost200Response

class TestOrganizationAcceptInvitationPost200Response(unittest.TestCase):
    """OrganizationAcceptInvitationPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationAcceptInvitationPost200Response:
        """Test OrganizationAcceptInvitationPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationAcceptInvitationPost200Response`
        """
        model = OrganizationAcceptInvitationPost200Response()
        if include_optional:
            return OrganizationAcceptInvitationPost200Response(
                invitation = None,
                member = None
            )
        else:
            return OrganizationAcceptInvitationPost200Response(
        )
        """

    def testOrganizationAcceptInvitationPost200Response(self):
        """Test OrganizationAcceptInvitationPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
