# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.admin_has_permission_post200_response import AdminHasPermissionPost200Response

class TestAdminHasPermissionPost200Response(unittest.TestCase):
    """AdminHasPermissionPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminHasPermissionPost200Response:
        """Test AdminHasPermissionPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminHasPermissionPost200Response`
        """
        model = AdminHasPermissionPost200Response()
        if include_optional:
            return AdminHasPermissionPost200Response(
                error = '',
                success = True
            )
        else:
            return AdminHasPermissionPost200Response(
                success = True,
        )
        """

    def testAdminHasPermissionPost200Response(self):
        """Test AdminHasPermissionPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
