# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.device_token_post400_response import DeviceTokenPost400Response

class TestDeviceTokenPost400Response(unittest.TestCase):
    """DeviceTokenPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceTokenPost400Response:
        """Test DeviceTokenPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceTokenPost400Response`
        """
        model = DeviceTokenPost400Response()
        if include_optional:
            return DeviceTokenPost400Response(
                error = 'authorization_pending',
                error_description = ''
            )
        else:
            return DeviceTokenPost400Response(
        )
        """

    def testDeviceTokenPost400Response(self):
        """Test DeviceTokenPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
