# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.username_api import UsernameApi


class TestUsernameApi(unittest.TestCase):
    """UsernameApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsernameApi()

    def tearDown(self) -> None:
        pass

    def test_is_username_available_post(self) -> None:
        """Test case for is_username_available_post

        """
        pass

    def test_sign_in_username_post(self) -> None:
        """Test case for sign_in_username_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
