# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.device_code import DeviceCode

class TestDeviceCode(unittest.TestCase):
    """DeviceCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceCode:
        """Test DeviceCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceCode`
        """
        model = DeviceCode()
        if include_optional:
            return DeviceCode(
                id = '',
                device_code = '',
                user_code = '',
                user_id = '',
                expires_at = '',
                status = '',
                last_polled_at = '',
                polling_interval = 1.337,
                client_id = '',
                scope = ''
            )
        else:
            return DeviceCode(
                device_code = '',
                user_code = '',
                expires_at = '',
                status = '',
        )
        """

    def testDeviceCode(self):
        """Test DeviceCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
