# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.organization_create_post_request import OrganizationCreatePostRequest

class TestOrganizationCreatePostRequest(unittest.TestCase):
    """OrganizationCreatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationCreatePostRequest:
        """Test OrganizationCreatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationCreatePostRequest`
        """
        model = OrganizationCreatePostRequest()
        if include_optional:
            return OrganizationCreatePostRequest(
                name = '',
                slug = '',
                user_id = '',
                logo = '',
                metadata = '',
                keep_current_active_organization = True
            )
        else:
            return OrganizationCreatePostRequest(
                name = '',
                slug = '',
        )
        """

    def testOrganizationCreatePostRequest(self):
        """Test OrganizationCreatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
