# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sso_register_post_request_saml_config import SsoRegisterPostRequestSamlConfig

class TestSsoRegisterPostRequestSamlConfig(unittest.TestCase):
    """SsoRegisterPostRequestSamlConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SsoRegisterPostRequestSamlConfig:
        """Test SsoRegisterPostRequestSamlConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SsoRegisterPostRequestSamlConfig`
        """
        model = SsoRegisterPostRequestSamlConfig()
        if include_optional:
            return SsoRegisterPostRequestSamlConfig(
                entry_point = '',
                cert = '',
                callback_url = '',
                audience = '',
                idp_metadata = better_auth.models._sso_register_post_request_saml_config_idp_metadata._sso_register_post_request_samlConfig_idpMetadata(
                    metadata = '', 
                    private_key = '', 
                    private_key_pass = '', 
                    is_assertion_encrypted = True, 
                    enc_private_key = '', 
                    enc_private_key_pass = '', ),
                sp_metadata = better_auth.models._sso_register_post_request_saml_config_sp_metadata._sso_register_post_request_samlConfig_spMetadata(
                    metadata = '', 
                    binding = '', 
                    private_key = '', 
                    private_key_pass = '', 
                    is_assertion_encrypted = True, 
                    enc_private_key = '', 
                    enc_private_key_pass = '', ),
                want_assertions_signed = True,
                signature_algorithm = '',
                digest_algorithm = '',
                identifier_format = '',
                private_key = '',
                decryption_pvk = '',
                additional_params = ''
            )
        else:
            return SsoRegisterPostRequestSamlConfig(
                entry_point = '',
                cert = '',
                callback_url = '',
                sp_metadata = better_auth.models._sso_register_post_request_saml_config_sp_metadata._sso_register_post_request_samlConfig_spMetadata(
                    metadata = '', 
                    binding = '', 
                    private_key = '', 
                    private_key_pass = '', 
                    is_assertion_encrypted = True, 
                    enc_private_key = '', 
                    enc_private_key_pass = '', ),
        )
        """

    def testSsoRegisterPostRequestSamlConfig(self):
        """Test SsoRegisterPostRequestSamlConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
