# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.oauth2_register_post200_response import Oauth2RegisterPost200Response

class TestOauth2RegisterPost200Response(unittest.TestCase):
    """Oauth2RegisterPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2RegisterPost200Response:
        """Test Oauth2RegisterPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2RegisterPost200Response`
        """
        model = Oauth2RegisterPost200Response()
        if include_optional:
            return Oauth2RegisterPost200Response(
                name = '',
                icon = '',
                metadata = { },
                client_id = '',
                client_secret = '',
                redirect_urls = [
                    ''
                    ],
                type = 'web',
                authentication_scheme = 'client_secret',
                disabled = false,
                user_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Oauth2RegisterPost200Response(
                name = '',
                client_id = '',
                client_secret = '',
                redirect_urls = [
                    ''
                    ],
                type = 'web',
                authentication_scheme = 'client_secret',
                disabled = false,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testOauth2RegisterPost200Response(self):
        """Test Oauth2RegisterPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
