# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.mcp_api import McpApi


class TestMcpApi(unittest.TestCase):
    """McpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = McpApi()

    def tearDown(self) -> None:
        pass

    def test_mcp_authorize_get(self) -> None:
        """Test case for mcp_authorize_get

        """
        pass

    def test_mcp_get_session_get(self) -> None:
        """Test case for mcp_get_session_get

        """
        pass

    def test_mcp_register_post(self) -> None:
        """Test case for mcp_register_post

        """
        pass

    def test_mcp_token_post(self) -> None:
        """Test case for mcp_token_post

        """
        pass

    def test_well_known_oauth_authorization_server_get(self) -> None:
        """Test case for well_known_oauth_authorization_server_get

        """
        pass

    def test_well_known_oauth_protected_resource_get(self) -> None:
        """Test case for well_known_oauth_protected_resource_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
