# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.email_otp_send_verification_otp_post_request import EmailOtpSendVerificationOtpPostRequest

class TestEmailOtpSendVerificationOtpPostRequest(unittest.TestCase):
    """EmailOtpSendVerificationOtpPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailOtpSendVerificationOtpPostRequest:
        """Test EmailOtpSendVerificationOtpPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailOtpSendVerificationOtpPostRequest`
        """
        model = EmailOtpSendVerificationOtpPostRequest()
        if include_optional:
            return EmailOtpSendVerificationOtpPostRequest(
                email = '',
                type = ''
            )
        else:
            return EmailOtpSendVerificationOtpPostRequest(
                email = '',
                type = '',
        )
        """

    def testEmailOtpSendVerificationOtpPostRequest(self):
        """Test EmailOtpSendVerificationOtpPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
