# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_generate_register_options_get200_response_pub_key_cred_params_inner import PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner

class TestPasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner(unittest.TestCase):
    """PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner:
        """Test PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner`
        """
        model = PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner()
        if include_optional:
            return PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner(
                type = '',
                alg = 1.337
            )
        else:
            return PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner(
        )
        """

    def testPasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner(self):
        """Test PasskeyGenerateRegisterOptionsGet200ResponsePubKeyCredParamsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
