# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.phone_number_forget_password_post_request import PhoneNumberForgetPasswordPostRequest

class TestPhoneNumberForgetPasswordPostRequest(unittest.TestCase):
    """PhoneNumberForgetPasswordPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumberForgetPasswordPostRequest:
        """Test PhoneNumberForgetPasswordPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumberForgetPasswordPostRequest`
        """
        model = PhoneNumberForgetPasswordPostRequest()
        if include_optional:
            return PhoneNumberForgetPasswordPostRequest(
                phone_number = ''
            )
        else:
            return PhoneNumberForgetPasswordPostRequest(
                phone_number = '',
        )
        """

    def testPhoneNumberForgetPasswordPostRequest(self):
        """Test PhoneNumberForgetPasswordPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
