# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sso_register_post200_response_oidc_config_mapping import SsoRegisterPost200ResponseOidcConfigMapping

class TestSsoRegisterPost200ResponseOidcConfigMapping(unittest.TestCase):
    """SsoRegisterPost200ResponseOidcConfigMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SsoRegisterPost200ResponseOidcConfigMapping:
        """Test SsoRegisterPost200ResponseOidcConfigMapping
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SsoRegisterPost200ResponseOidcConfigMapping`
        """
        model = SsoRegisterPost200ResponseOidcConfigMapping()
        if include_optional:
            return SsoRegisterPost200ResponseOidcConfigMapping(
                id = '',
                email = '',
                email_verified = '',
                name = '',
                image = '',
                extra_fields = {
                    'key' : ''
                    }
            )
        else:
            return SsoRegisterPost200ResponseOidcConfigMapping(
                id = '',
                email = '',
                name = '',
        )
        """

    def testSsoRegisterPost200ResponseOidcConfigMapping(self):
        """Test SsoRegisterPost200ResponseOidcConfigMapping"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
