# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sso_register_post200_response_oidc_config import SsoRegisterPost200ResponseOidcConfig

class TestSsoRegisterPost200ResponseOidcConfig(unittest.TestCase):
    """SsoRegisterPost200ResponseOidcConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SsoRegisterPost200ResponseOidcConfig:
        """Test SsoRegisterPost200ResponseOidcConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SsoRegisterPost200ResponseOidcConfig`
        """
        model = SsoRegisterPost200ResponseOidcConfig()
        if include_optional:
            return SsoRegisterPost200ResponseOidcConfig(
                issuer = '',
                pkce = True,
                client_id = '',
                client_secret = '',
                authorization_endpoint = '',
                discovery_endpoint = '',
                user_info_endpoint = '',
                scopes = [
                    ''
                    ],
                token_endpoint = '',
                token_endpoint_authentication = 'client_secret_post',
                jwks_endpoint = '',
                mapping = better_auth.models._sso_register_post_200_response_oidc_config_mapping._sso_register_post_200_response_oidcConfig_mapping(
                    id = '', 
                    email = '', 
                    email_verified = '', 
                    name = '', 
                    image = '', 
                    extra_fields = {
                        'key' : ''
                        }, )
            )
        else:
            return SsoRegisterPost200ResponseOidcConfig(
                issuer = '',
                pkce = True,
                client_id = '',
                client_secret = '',
                discovery_endpoint = '',
        )
        """

    def testSsoRegisterPost200ResponseOidcConfig(self):
        """Test SsoRegisterPost200ResponseOidcConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
