# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_in_username_post200_response import SignInUsernamePost200Response

class TestSignInUsernamePost200Response(unittest.TestCase):
    """SignInUsernamePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInUsernamePost200Response:
        """Test SignInUsernamePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInUsernamePost200Response`
        """
        model = SignInUsernamePost200Response()
        if include_optional:
            return SignInUsernamePost200Response(
                token = '',
                user = better_auth.models.user.User(
                    id = '', 
                    name = '', 
                    email = '', 
                    email_verified = True, 
                    image = '', 
                    created_at = 'Generated at runtime', 
                    updated_at = 'Generated at runtime', 
                    two_factor_enabled = True, 
                    username = '', 
                    display_username = '', 
                    is_anonymous = True, 
                    phone_number = '', 
                    phone_number_verified = True, 
                    role = '', 
                    banned = True, 
                    ban_reason = '', 
                    ban_expires = '', )
            )
        else:
            return SignInUsernamePost200Response(
                token = '',
                user = better_auth.models.user.User(
                    id = '', 
                    name = '', 
                    email = '', 
                    email_verified = True, 
                    image = '', 
                    created_at = 'Generated at runtime', 
                    updated_at = 'Generated at runtime', 
                    two_factor_enabled = True, 
                    username = '', 
                    display_username = '', 
                    is_anonymous = True, 
                    phone_number = '', 
                    phone_number_verified = True, 
                    role = '', 
                    banned = True, 
                    ban_reason = '', 
                    ban_expires = '', ),
        )
        """

    def testSignInUsernamePost200Response(self):
        """Test SignInUsernamePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
