# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_in_sso_post_request import SignInSsoPostRequest

class TestSignInSsoPostRequest(unittest.TestCase):
    """SignInSsoPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInSsoPostRequest:
        """Test SignInSsoPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInSsoPostRequest`
        """
        model = SignInSsoPostRequest()
        if include_optional:
            return SignInSsoPostRequest(
                email = '',
                issuer = '',
                provider_id = '',
                callback_url = '',
                error_callback_url = '',
                new_user_callback_url = ''
            )
        else:
            return SignInSsoPostRequest(
                callback_url = '',
        )
        """

    def testSignInSsoPostRequest(self):
        """Test SignInSsoPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
