# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_generate_register_options_get200_response_exclude_credentials_inner import PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner

class TestPasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner(unittest.TestCase):
    """PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner:
        """Test PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner`
        """
        model = PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner()
        if include_optional:
            return PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner(
                id = '',
                type = '',
                transports = [
                    ''
                    ]
            )
        else:
            return PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner(
        )
        """

    def testPasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner(self):
        """Test PasskeyGenerateRegisterOptionsGet200ResponseExcludeCredentialsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
