# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_in_oauth2_post200_response import SignInOauth2Post200Response

class TestSignInOauth2Post200Response(unittest.TestCase):
    """SignInOauth2Post200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInOauth2Post200Response:
        """Test SignInOauth2Post200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInOauth2Post200Response`
        """
        model = SignInOauth2Post200Response()
        if include_optional:
            return SignInOauth2Post200Response(
                url = '',
                redirect = True
            )
        else:
            return SignInOauth2Post200Response(
        )
        """

    def testSignInOauth2Post200Response(self):
        """Test SignInOauth2Post200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
