# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.account_info_post200_response import AccountInfoPost200Response

class TestAccountInfoPost200Response(unittest.TestCase):
    """AccountInfoPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountInfoPost200Response:
        """Test AccountInfoPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountInfoPost200Response`
        """
        model = AccountInfoPost200Response()
        if include_optional:
            return AccountInfoPost200Response(
                user = better_auth.models._account_info_post_200_response_user._account_info_post_200_response_user(
                    id = '', 
                    name = '', 
                    email = '', 
                    image = '', 
                    email_verified = True, ),
                data = {
                    'key' : null
                    }
            )
        else:
            return AccountInfoPost200Response(
                user = better_auth.models._account_info_post_200_response_user._account_info_post_200_response_user(
                    id = '', 
                    name = '', 
                    email = '', 
                    image = '', 
                    email_verified = True, ),
                data = {
                    'key' : null
                    },
        )
        """

    def testAccountInfoPost200Response(self):
        """Test AccountInfoPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
