# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.oidc_api import OidcApi


class TestOidcApi(unittest.TestCase):
    """OidcApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OidcApi()

    def tearDown(self) -> None:
        pass

    def test_oauth2_authorize_get(self) -> None:
        """Test case for oauth2_authorize_get

        """
        pass

    def test_oauth2_client_id_get(self) -> None:
        """Test case for oauth2_client_id_get

        """
        pass

    def test_oauth2_consent_post(self) -> None:
        """Test case for oauth2_consent_post

        """
        pass

    def test_oauth2_register_post(self) -> None:
        """Test case for oauth2_register_post

        """
        pass

    def test_oauth2_token_post(self) -> None:
        """Test case for oauth2_token_post

        """
        pass

    def test_oauth2_userinfo_get(self) -> None:
        """Test case for oauth2_userinfo_get

        """
        pass

    def test_well_known_openid_configuration_get(self) -> None:
        """Test case for well_known_openid_configuration_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
