# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.oauth2_consent_post200_response import Oauth2ConsentPost200Response

class TestOauth2ConsentPost200Response(unittest.TestCase):
    """Oauth2ConsentPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2ConsentPost200Response:
        """Test Oauth2ConsentPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2ConsentPost200Response`
        """
        model = Oauth2ConsentPost200Response()
        if include_optional:
            return Oauth2ConsentPost200Response(
                redirect_uri = ''
            )
        else:
            return Oauth2ConsentPost200Response(
                redirect_uri = '',
        )
        """

    def testOauth2ConsentPost200Response(self):
        """Test Oauth2ConsentPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
