# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.list_accounts_get200_response_inner import ListAccountsGet200ResponseInner

class TestListAccountsGet200ResponseInner(unittest.TestCase):
    """ListAccountsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAccountsGet200ResponseInner:
        """Test ListAccountsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAccountsGet200ResponseInner`
        """
        model = ListAccountsGet200ResponseInner()
        if include_optional:
            return ListAccountsGet200ResponseInner(
                id = '',
                provider_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                account_id = '',
                scopes = [
                    ''
                    ]
            )
        else:
            return ListAccountsGet200ResponseInner(
                id = '',
                provider_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                account_id = '',
                scopes = [
                    ''
                    ],
        )
        """

    def testListAccountsGet200ResponseInner(self):
        """Test ListAccountsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
