# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.organization_invite_member_post_request import OrganizationInviteMemberPostRequest

class TestOrganizationInviteMemberPostRequest(unittest.TestCase):
    """OrganizationInviteMemberPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationInviteMemberPostRequest:
        """Test OrganizationInviteMemberPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationInviteMemberPostRequest`
        """
        model = OrganizationInviteMemberPostRequest()
        if include_optional:
            return OrganizationInviteMemberPostRequest(
                email = '',
                role = '',
                organization_id = '',
                resend = True,
                team_id = ''
            )
        else:
            return OrganizationInviteMemberPostRequest(
                email = '',
                role = '',
                team_id = '',
        )
        """

    def testOrganizationInviteMemberPostRequest(self):
        """Test OrganizationInviteMemberPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
