# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_generate_register_options_get200_response_authenticator_selection import PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection

class TestPasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection(unittest.TestCase):
    """PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection:
        """Test PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection`
        """
        model = PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection()
        if include_optional:
            return PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection(
                authenticator_attachment = '',
                require_resident_key = True,
                user_verification = ''
            )
        else:
            return PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection(
        )
        """

    def testPasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection(self):
        """Test PasskeyGenerateRegisterOptionsGet200ResponseAuthenticatorSelection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
