# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_out_post200_response import SignOutPost200Response

class TestSignOutPost200Response(unittest.TestCase):
    """SignOutPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignOutPost200Response:
        """Test SignOutPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignOutPost200Response`
        """
        model = SignOutPost200Response()
        if include_optional:
            return SignOutPost200Response(
                success = True
            )
        else:
            return SignOutPost200Response(
        )
        """

    def testSignOutPost200Response(self):
        """Test SignOutPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
