# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_account_info_post(self) -> None:
        """Test case for account_info_post

        """
        pass

    def test_change_email_post(self) -> None:
        """Test case for change_email_post

        """
        pass

    def test_change_password_post(self) -> None:
        """Test case for change_password_post

        """
        pass

    def test_delete_user_callback_get(self) -> None:
        """Test case for delete_user_callback_get

        """
        pass

    def test_delete_user_post(self) -> None:
        """Test case for delete_user_post

        """
        pass

    def test_error_get(self) -> None:
        """Test case for error_get

        """
        pass

    def test_forget_password_post(self) -> None:
        """Test case for forget_password_post

        """
        pass

    def test_get_access_token_post(self) -> None:
        """Test case for get_access_token_post

        """
        pass

    def test_get_session_get(self) -> None:
        """Test case for get_session_get

        """
        pass

    def test_link_social_post(self) -> None:
        """Test case for link_social_post

        """
        pass

    def test_list_accounts_get(self) -> None:
        """Test case for list_accounts_get

        """
        pass

    def test_list_sessions_get(self) -> None:
        """Test case for list_sessions_get

        """
        pass

    def test_ok_get(self) -> None:
        """Test case for ok_get

        """
        pass

    def test_refresh_token_post(self) -> None:
        """Test case for refresh_token_post

        """
        pass

    def test_request_password_reset_post(self) -> None:
        """Test case for request_password_reset_post

        """
        pass

    def test_reset_password_post(self) -> None:
        """Test case for reset_password_post

        """
        pass

    def test_reset_password_token_get(self) -> None:
        """Test case for reset_password_token_get

        """
        pass

    def test_revoke_other_sessions_post(self) -> None:
        """Test case for revoke_other_sessions_post

        """
        pass

    def test_revoke_session_post(self) -> None:
        """Test case for revoke_session_post

        """
        pass

    def test_revoke_sessions_post(self) -> None:
        """Test case for revoke_sessions_post

        """
        pass

    def test_send_verification_email_post(self) -> None:
        """Test case for send_verification_email_post

        """
        pass

    def test_sign_in_email_post(self) -> None:
        """Test case for sign_in_email_post

        """
        pass

    def test_sign_out_post(self) -> None:
        """Test case for sign_out_post

        """
        pass

    def test_sign_up_email_post(self) -> None:
        """Test case for sign_up_email_post

        """
        pass

    def test_social_sign_in(self) -> None:
        """Test case for social_sign_in

        """
        pass

    def test_unlink_account_post(self) -> None:
        """Test case for unlink_account_post

        """
        pass

    def test_update_user_post(self) -> None:
        """Test case for update_user_post

        """
        pass

    def test_verify_email_get(self) -> None:
        """Test case for verify_email_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
