# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.organization_check_slug_post_request import OrganizationCheckSlugPostRequest

class TestOrganizationCheckSlugPostRequest(unittest.TestCase):
    """OrganizationCheckSlugPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationCheckSlugPostRequest:
        """Test OrganizationCheckSlugPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationCheckSlugPostRequest`
        """
        model = OrganizationCheckSlugPostRequest()
        if include_optional:
            return OrganizationCheckSlugPostRequest(
                slug = ''
            )
        else:
            return OrganizationCheckSlugPostRequest(
                slug = '',
        )
        """

    def testOrganizationCheckSlugPostRequest(self):
        """Test OrganizationCheckSlugPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
