# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.sso_api import SsoApi


class TestSsoApi(unittest.TestCase):
    """SsoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SsoApi()

    def tearDown(self) -> None:
        pass

    def test_sign_in_sso_post(self) -> None:
        """Test case for sign_in_sso_post

        """
        pass

    def test_sso_callback_provider_id_get(self) -> None:
        """Test case for sso_callback_provider_id_get

        """
        pass

    def test_sso_register_post(self) -> None:
        """Test case for sso_register_post

        """
        pass

    def test_sso_saml2_callback_provider_id_post(self) -> None:
        """Test case for sso_saml2_callback_provider_id_post

        """
        pass

    def test_sso_saml2_sp_metadata_get(self) -> None:
        """Test case for sso_saml2_sp_metadata_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
