# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_in_magic_link_post_request import SignInMagicLinkPostRequest

class TestSignInMagicLinkPostRequest(unittest.TestCase):
    """SignInMagicLinkPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInMagicLinkPostRequest:
        """Test SignInMagicLinkPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInMagicLinkPostRequest`
        """
        model = SignInMagicLinkPostRequest()
        if include_optional:
            return SignInMagicLinkPostRequest(
                email = '',
                name = '',
                callback_url = '',
                new_user_callback_url = '',
                error_callback_url = ''
            )
        else:
            return SignInMagicLinkPostRequest(
                email = '',
        )
        """

    def testSignInMagicLinkPostRequest(self):
        """Test SignInMagicLinkPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
