# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.send_verification_email_post200_response import SendVerificationEmailPost200Response

class TestSendVerificationEmailPost200Response(unittest.TestCase):
    """SendVerificationEmailPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendVerificationEmailPost200Response:
        """Test SendVerificationEmailPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendVerificationEmailPost200Response`
        """
        model = SendVerificationEmailPost200Response()
        if include_optional:
            return SendVerificationEmailPost200Response(
                status = True
            )
        else:
            return SendVerificationEmailPost200Response(
        )
        """

    def testSendVerificationEmailPost200Response(self):
        """Test SendVerificationEmailPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
