# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.organization_get_invitation_get200_response import OrganizationGetInvitationGet200Response

class TestOrganizationGetInvitationGet200Response(unittest.TestCase):
    """OrganizationGetInvitationGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationGetInvitationGet200Response:
        """Test OrganizationGetInvitationGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationGetInvitationGet200Response`
        """
        model = OrganizationGetInvitationGet200Response()
        if include_optional:
            return OrganizationGetInvitationGet200Response(
                id = '',
                email = '',
                role = '',
                organization_id = '',
                inviter_id = '',
                status = '',
                expires_at = '',
                organization_name = '',
                organization_slug = '',
                inviter_email = ''
            )
        else:
            return OrganizationGetInvitationGet200Response(
                id = '',
                email = '',
                role = '',
                organization_id = '',
                inviter_id = '',
                status = '',
                expires_at = '',
                organization_name = '',
                organization_slug = '',
                inviter_email = '',
        )
        """

    def testOrganizationGetInvitationGet200Response(self):
        """Test OrganizationGetInvitationGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
