# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.link_social_post_request import LinkSocialPostRequest

class TestLinkSocialPostRequest(unittest.TestCase):
    """LinkSocialPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkSocialPostRequest:
        """Test LinkSocialPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkSocialPostRequest`
        """
        model = LinkSocialPostRequest()
        if include_optional:
            return LinkSocialPostRequest(
                callback_url = '',
                provider = '',
                id_token = better_auth.models._link_social_post_request_id_token._link_social_post_request_idToken(
                    token = '', 
                    nonce = '', 
                    access_token = '', 
                    refresh_token = '', 
                    scopes = [
                        null
                        ], ),
                request_sign_up = True,
                scopes = [
                    null
                    ],
                error_callback_url = '',
                disable_redirect = True
            )
        else:
            return LinkSocialPostRequest(
                provider = '',
        )
        """

    def testLinkSocialPostRequest(self):
        """Test LinkSocialPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
