# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.admin_has_permission_post_request import AdminHasPermissionPostRequest

class TestAdminHasPermissionPostRequest(unittest.TestCase):
    """AdminHasPermissionPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminHasPermissionPostRequest:
        """Test AdminHasPermissionPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminHasPermissionPostRequest`
        """
        model = AdminHasPermissionPostRequest()
        if include_optional:
            return AdminHasPermissionPostRequest(
                permission = None,
                permissions = None
            )
        else:
            return AdminHasPermissionPostRequest(
                permissions = None,
        )
        """

    def testAdminHasPermissionPostRequest(self):
        """Test AdminHasPermissionPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
