# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.phone_number_request_password_reset_post_request import PhoneNumberRequestPasswordResetPostRequest

class TestPhoneNumberRequestPasswordResetPostRequest(unittest.TestCase):
    """PhoneNumberRequestPasswordResetPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumberRequestPasswordResetPostRequest:
        """Test PhoneNumberRequestPasswordResetPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumberRequestPasswordResetPostRequest`
        """
        model = PhoneNumberRequestPasswordResetPostRequest()
        if include_optional:
            return PhoneNumberRequestPasswordResetPostRequest(
                phone_number = ''
            )
        else:
            return PhoneNumberRequestPasswordResetPostRequest(
                phone_number = '',
        )
        """

    def testPhoneNumberRequestPasswordResetPostRequest(self):
        """Test PhoneNumberRequestPasswordResetPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
