# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.jwks_get200_response_keys_inner import JwksGet200ResponseKeysInner

class TestJwksGet200ResponseKeysInner(unittest.TestCase):
    """JwksGet200ResponseKeysInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JwksGet200ResponseKeysInner:
        """Test JwksGet200ResponseKeysInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JwksGet200ResponseKeysInner`
        """
        model = JwksGet200ResponseKeysInner()
        if include_optional:
            return JwksGet200ResponseKeysInner(
                kid = '',
                kty = '',
                alg = '',
                use = 'sig',
                n = '',
                e = '',
                crv = '',
                x = '',
                y = ''
            )
        else:
            return JwksGet200ResponseKeysInner(
                kid = '',
                kty = '',
                alg = '',
        )
        """

    def testJwksGet200ResponseKeysInner(self):
        """Test JwksGet200ResponseKeysInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
