# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.change_password_post_request import ChangePasswordPostRequest

class TestChangePasswordPostRequest(unittest.TestCase):
    """ChangePasswordPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangePasswordPostRequest:
        """Test ChangePasswordPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangePasswordPostRequest`
        """
        model = ChangePasswordPostRequest()
        if include_optional:
            return ChangePasswordPostRequest(
                new_password = '',
                current_password = '',
                revoke_other_sessions = True
            )
        else:
            return ChangePasswordPostRequest(
                new_password = '',
                current_password = '',
        )
        """

    def testChangePasswordPostRequest(self):
        """Test ChangePasswordPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
