# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.oauth_application import OauthApplication

class TestOauthApplication(unittest.TestCase):
    """OauthApplication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OauthApplication:
        """Test OauthApplication
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OauthApplication`
        """
        model = OauthApplication()
        if include_optional:
            return OauthApplication(
                id = '',
                name = '',
                icon = '',
                metadata = '',
                client_id = '',
                client_secret = '',
                redirect_urls = '',
                type = '',
                disabled = True,
                user_id = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return OauthApplication(
        )
        """

    def testOauthApplication(self):
        """Test OauthApplication"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
